// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0HwWL9y3cAKHrc7y1LO_FnS8Wg5FNx-Y',
    appId: '1:302601394691:web:9abdf06c633e4eb30c4c36',
    messagingSenderId: '302601394691',
    projectId: 'real-time-maps-b5cd0',
    authDomain: 'real-time-maps-b5cd0.firebaseapp.com',
    databaseURL: 'https://real-time-maps-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-maps-b5cd0.firebasestorage.app',
    measurementId: 'G-QK76L7F2WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZ_UAmSZpo8vOEXRNUmhMoJO5aFCxLxs',
    appId: '1:302601394691:android:3e022a54a0362bac0c4c36',
    messagingSenderId: '302601394691',
    projectId: 'real-time-maps-b5cd0',
    databaseURL: 'https://real-time-maps-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-maps-b5cd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5b4f-c0P71P27XcLwB-7tK9qY2nGHo4c',
    appId: '1:302601394691:ios:9cdc9c78f400f56d0c4c36',
    messagingSenderId: '302601394691',
    projectId: 'real-time-maps-b5cd0',
    databaseURL: 'https://real-time-maps-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-maps-b5cd0.firebasestorage.app',
    iosBundleId: 'com.example.userbapp.userBApp',
  );
}
